server:
  port: 8002

spring:
  datasource:
    platform: usershares
    driverClassName: org.h2.Driver
    url : jdbc:h2:file:./src/main/resources/static/usershares
  jpa.hibernate.ddl-auto: update
  application:
    name: users-service
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health